<?php

use App\Enums\CabinetEnum;
use App\Enums\PrefectureEnum;
use App\Utils\TableConfigManager;

return [
    'table' => 'points',
    'settings' => [
        'soft_delete' => true,
        'by_user' => false,
        'index' => null,
        'unique' => null,
    ],
    'columns' => [
        'key' => [
            'label' => '地点キー',
            'type' => TableConfigManager::TYPE_VARCHAR,
            'digit' => 64,
            'decimal_places' => null,
            'min' => null,
            'max' => null,
            'unique' => true,
            'index' => false,
            'required' => true,
            'enum' => null,
            'default_value' => null,
            'sample_value' => 'togura-station',
            'comment' => '',
            'foreign_table' => null,
            'foreign_column' => null,
        ],
        'name' => [
            'label' => '地点名',
            'type' => TableConfigManager::TYPE_VARCHAR,
            'digit' => 128,
            'decimal_places' => null,
            'min' => null,
            'max' => null,
            'unique' => false,
            'index' => false,
            'required' => true,
            'enum' => null,
            'default_value' => null,
            'sample_value' => '戸倉駅',
            'comment' => '',
            'foreign_table' => null,
            'foreign_column' => null,
        ],
        'url' => [
            'label' => 'URL',
            'type' => TableConfigManager::TYPE_VARCHAR,
            'digit' => 256,
            'decimal_places' => null,
            'min' => null,
            'max' => null,
            'unique' => false,
            'index' => false,
            'required' => false,
            'enum' => null,
            'default_value' => null,
            'sample_value' => '戸倉駅',
            'comment' => '',
            'foreign_table' => null,
            'foreign_column' => null,
        ],
        'pick_up_required_time' => [
            'label' => '送迎までにかかる時間',
            'type' => TableConfigManager::TYPE_UNSIGNED_TINYINT,
            'digit' => null,
            'decimal_places' => null,
            'min' => null,
            'max' => null,
            'unique' => false,
            'index' => false,
            'required' => true,
            'enum' => null,
            'default_value' => null,
            'sample_value' => 15,
            'comment' => '',
            'foreign_table' => null,
            'foreign_column' => null,
        ],
    ],
];
