<?php

use App\Enums\ReservationAnswerStatusEnum;
use App\Utils\TableConfigManager;

return [
    'table' => 'reservations',
    'settings' => [
        'soft_delete' => true,
        'by_user' => false,
        'index' => null,
        'unique' => null,
    ],
    'columns' => [
        'user_id' => [
            'label' => 'ユーザID',
            'type' => TableConfigManager::TYPE_UNSIGNED_BIGINT,
            'digit' => null,
            'decimal_places' => null,
            'min' => null,
            'max' => null,
            'unique' => false,
            'index' => true,
            'required' => true,
            'enum' => null,
            'default_value' => null,
            'sample_value' => '12345',
            'comment' => '',
            'foreign_table' => 'users',
            'foreign_column' => 'id',
        ],
        'status' => [
            'label' => 'ステータス',
            'type' => TableConfigManager::TYPE_ENUM,
            'digit' => null,
            'decimal_places' => null,
            'min' => null,
            'max' => null,
            'unique' => false,
            'index' => true,
            'required' => false,
            'enum' => ReservationAnswerStatusEnum::class,
            'default_value' => null,
            'sample_value' => 'dispatching',
            'comment' => '',
            'foreign_table' => null,
            'foreign_column' => null,
        ],
        'name' => [
            'label' => '予約名',
            'type' => TableConfigManager::TYPE_VARCHAR,
            'digit' => 128,
            'decimal_places' => null,
            'min' => null,
            'max' => null,
            'unique' => false,
            'index' => false,
            'required' => true,
            'enum' => null,
            'default_value' => null,
            'sample_value' => '温泉太郎',
            'comment' => '',
            'foreign_table' => null,
            'foreign_column' => null,
        ],
        'tel' => [
            'label' => '電話番号',
            'type' => TableConfigManager::TYPE_VARCHAR,
            'digit' => 16,
            'decimal_places' => null,
            'min' => null,
            'max' => null,
            'unique' => false,
            'index' => false,
            'required' => true,
            'enum' => null,
            'default_value' => null,
            'sample_value' => '090-11112-222',
            'comment' => '',
            'foreign_table' => null,
            'foreign_column' => null,
        ],
        'departure_point_id' => [
            'label' => '出発地点ID',
            'type' => TableConfigManager::TYPE_UNSIGNED_BIGINT,
            'digit' => null,
            'decimal_places' => null,
            'min' => null,
            'max' => null,
            'unique' => false,
            'index' => true,
            'required' => true,
            'enum' => null,
            'default_value' => null,
            'sample_value' => 1,
            'comment' => '',
            'foreign_table' => 'points',
            'foreign_column' => 'id',
        ],
        'arrival_point_id' => [
            'label' => '到着地点ID',
            'type' => TableConfigManager::TYPE_UNSIGNED_BIGINT,
            'digit' => null,
            'decimal_places' => null,
            'min' => null,
            'max' => null,
            'unique' => false,
            'index' => true,
            'required' => true,
            'enum' => null,
            'default_value' => null,
            'sample_value' => 2,
            'comment' => '',
            'foreign_table' => 'points',
            'foreign_column' => 'id',
        ],
        'picture' => [
            'label' => '画像URL',
            'type' => TableConfigManager::TYPE_VARCHAR,
            'digit' => 256,
            'decimal_places' => null,
            'min' => null,
            'max' => null,
            'unique' => false,
            'index' => false,
            'required' => false,
            'enum' => null,
            'default_value' => null,
            'sample_value' => 'https://xxxx.yyy',
            'comment' => '',
            'foreign_table' => null,
            'foreign_column' => null,
        ],
        'pick_up_scheduled_time' => [
            'label' => '迎車予定時刻',
            'type' => TableConfigManager::TYPE_DATETIME,
            'digit' => null,
            'decimal_places' => null,
            'min' => null,
            'max' => null,
            'unique' => false,
            'index' => false,
            'required' => true,
            'enum' => null,
            'default_value' => null,
            'sample_value' => '2000-10-10 23:59:59',
            'comment' => '',
            'foreign_table' => null,
            'foreign_column' => null,
        ],
    ],
];
